server:
  port: 8085

spring:
  application:
    name: verification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/aegisops
    username: aegisops
    password: aegisops_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
