server:
  port: 8083

spring:
  application:
    name: workflow-orchestrator
  grpc:
    client:
      channels:
        retrieval:
          address: "static://localhost:50051"
          negotiation-type: PLAINTEXT

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
